# Nixpacks configuration to automate Laravel permissions on deploy and start
[phases.build]
cmds = [
    "...",
    "chmod -R 777 storage bootstrap/cache"
]

[start]
cmd = "chmod -R 777 storage bootstrap/cache && php artisan storage:link --force && php artisan queue:work --daemon --tries=3 & php-fpm -y /assets/php-fpm.conf & nginx -c /app/nginx.conf"
